version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key
      - SQLALCHEMY_DATABASE_URI=sqlite:///app.db
    restart: always